### PR TITLE
Some README improvements

### PR DESCRIPTION
**Pull request by fintarin**

### CODE REVIEW

**Comment by artrayme** [comment]
Resolve the conflict, please.

**Comment by fintarin** [comment]
Accept my pr, please!!!!!!!!!!!!!!!!

**Comment by artrayme** [comment]
No, because the tests failed.

**Comment by artrayme** [comment]
But I like these changes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fintarin** [comment]
The trap has slammed.

**Pull request merged**
